stages:
  train:
    cmd: python src/train.py
    deps:
    - data/Final_Dataset
    - src/train.py
    - src/utils.py
    - params.yaml
    outs:
    - models/model.pt
    - reports/train_params.yaml:
        cache: false
    metrics:
    - reports/train_metrics.csv:
        cache: false
