model_type: yolov8s.pt
pretrained: True
seed: 0
imgsz: 640 
batch: 16 
epochs: 6
optimizer: auto# other choices=['SGD', 'Adam', 'AdamW', 'RMSProp']
lr0: 0.01  # learning rate 
name: vehicle_type # experiment name
